##The given two function are used to calculate the inverse of matrix and if the inverse is already
## calculated then it does not calculate it again which saves repeated computation.


##The first function, makeCacheMatrix creates a special a list containing a function to
##1.set the value of the matrix
##2.get the value of the matrix
##3.set the value of the inverse of matrix 'x'
##4.get the value of the inverse of matrix 'x'
makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) i <<- solve
  getinverse <- function() i
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}



##The second function takes the list generated by the makeCacheMatrix as the argument.
##It first checks wheather the value of the inverse of matrix is present in cache by checking the value 
##of 'i' for null.If it is not null therefore it skips the calculating and retrieves the value from the 
##cache.Otherwise, it calculates the inverse using built-in solve function and then sets the value in the 
##cache using setinverse function.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  i <- x$getinverse()
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  message("Calculating it now (no cache)")
  data <- x$get()
  i <- solve(data, ...)
  x$setinverse(i)
  i
}
